spring:
  application:
    name: microservice-sidecar
server:
  port: 8070   #eureka的默认端口
  
#eureka 配置
eureka:
  client:
    service-url:
       defaultZone: http://user:password123@localhost:8761/eureka    #这个是eureka server授权的模式
  instance:
    prefer-ip-address: true  #使用ip  而不是主机名

#sidecar配置
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json

  


    



    
    
    
    
    
    