spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040   #eureka的默认端口
  
#eureka 配置
eureka:
  client:
    service-url:
       defaultZone: http://user:password123@localhost:8761/eureka    #这个是eureka server授权的模式
  instance:
    prefer-ip-address: true  #使用ip  而不是主机名
  

  


    



    
    
    
    
    
    