management:
  port: 8081   # 管理端口
spring:
  application:
    name: microservice-comsumer-movie-ribbon-with-hystrix3
server:
  port: 8010   #消费者只需要进行端口的配置     访问端口
  context-path: /ribbon
#user: 
#  userServicePath: http://localhost:7900/simple/   对用户微服务硬编码的修改
#3. 这个是eureka的配置  这个表示的是注册到的eureka server服务端的地址
eureka:
  client:
    healthcheck:    #健康检查   需要spring-boot-starter-actuator依赖
       enabled: true
    serviceUrl:
       defaultZone: http://user:password123@localhost:8761/eureka   #这里是使用curl(使用的是http的方式进行认证)的方式进行认证
#      defaultZone: http://localhost:8761/eureka/  这里是没有进行eureka server认证时的地址
      
     
#  ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}.  这个是默认的显示形式
  instance:
    prefer-ip-address: true   #这里表示使用ip进行注册   默认是false 在服务的注册鼠标移上去的时候就是一ip的形势进行显示的
    metadata-map:
      management.port: 8081  #与上面的一致  turbine中的配置
#    home-page-url-path: /ribbon    #http://localhost:8761/eureka/apps -> homoeUrlPage: http://192.168.1.144:8010/(不配置时) http://localhost:8010/ribbon/hystrix.stream
#设置请求的超时时间    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

# http://localhost:8010/ribbon  --首页的访问地址

    
    
    