server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiranlyf/spring-cloud #.git后缀名可以不要
          username:    #进行用户名和密码的验证
          password: 
  application:
    name:  microservice-config-server-eureka #vip 的名称

#eureka配置   这里就是将config server注册到eureka上面
eureka:
  client:
#    healthcheck:   这个是进行安全监测   
#       enabled: true
    serviceUrl:
       defaultZone: http://user:password123@localhost:8761/eureka 
  instance:    #默认使用的是主机名的名称   配置之后就是使用的是ip地址进行显示
    prefer-ip-address: true 
      
  
      
         

