server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiranlyf/spring-cloud #.git后缀名可以不要
          username:    #进行用户名和密码的验证
          password: 
         
#加密解密 jce_policy-8 配置
encrypt:
  key: foo

