server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none  #jpa是依赖Hibernate的   这里设置ddl启动的时候时候生成语句
  datasource:
    platform: h2   #标识使用的数据源
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  #打印sql  同时打印参数之类的
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.shiran: DEBUG
    
   
    
   
 